## Role and RoleBinding for launch k8s-dind-confing in codefresh namespace
##   Change namespace if you plan to run it in different namespace
## usage:
##    kubectl apply -f rbac.yaml
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: codefresh-dind
rules:
- apiGroups: [""]
  resources: ["services","pods","configmaps","secrets"]
  verbs: ["get", "list","watch", "create","update", "patch","delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: codefresh-dind-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: codefresh-dind
  apiGroup: rbac.authorization.k8s.io
