##
## RUNTIME CONFIGURATION
##
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codefresh-resource-limitations
data:
  resource-limitations.json: |
    {}
---
apiVersion: v1
kind: Secret
metadata:
  name: codefresh-internal-registry
stringData:
  internal-registry.json: |
    {
      "kind": "standard" ,
      "domain": "{{CF_REGISTRY_DOMAIN}}",
      "username": "{{CF_REGISTRY_USER}}",
      "password": "{{REGISTRY_TOKEN}}",
      "repositoryPrefix": "internal",
      "connection": {
        "protocol": "{{CF_REGISTRY_PROTOCOL}}"
      }
    }
  additional-internal-registries.json: |
    []